# Generated by Django 2.1.5 on 2019-02-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190207_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
