# Generated by Django 2.1.5 on 2019-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100)),
                ('seat_count', models.TextField(max_length=100)),
                ('seat_numbers', models.TextField(max_length=100)),
                ('total_amount', models.TextField(max_length=100)),
            ],
        ),
    ]
