# Generated by Django 2.1.5 on 2019-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='seat_count',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seat_numbers',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='total_amount',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
