# Generated by Django 2.1.5 on 2019-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190228_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
