# Generated by Django 2.1.5 on 2019-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tickets_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPrice',
            fields=[
                ('price', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
