# Generated by Django 2.1.5 on 2019-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_addmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
